/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sales.generator.view;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import com.sales.generator.controller.ControllerOfSalesInvoice;
import com.sales.generator.model.Invoice_Generator;
import com.sales.generator.model.InvoicesTable;
import com.sales.generator.model.LinesTable;
public class FrameOfInvoice extends javax.swing.JFrame {

    /**
     * Creates new form FrameOfInvoice
     * 
     */
    public FrameOfInvoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfInvoice = new javax.swing.JTable();
        tableOfInvoice.getSelectionModel().addListSelectionListener(InvoiceController);
        createNewIvoice = new javax.swing.JButton();
        createNewIvoice.addActionListener(InvoiceController);
        deleteInvoice = new javax.swing.JButton();
        deleteInvoice.addActionListener(InvoiceController);
        invoiceNumber = new javax.swing.JLabel();
        invoiceDate = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();
        totalOfInvoice = new javax.swing.JLabel();
        InvoiceNumLbl = new javax.swing.JLabel();
        invoiceDateLable = new javax.swing.JLabel();
        customerNameLable = new javax.swing.JLabel();
        totalOfInvoiceLable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lineTable = new javax.swing.JTable();
        CreateItem = new javax.swing.JButton();
        CreateItem.addActionListener(InvoiceController);
        deleteItem = new javax.swing.JButton();
        deleteItem.addActionListener(InvoiceController);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFile = new javax.swing.JMenuItem();
        loadFile.addActionListener(InvoiceController);
        saveFile = new javax.swing.JMenuItem();
        saveFile.addActionListener(InvoiceController);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableOfInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableOfInvoice);

        createNewIvoice.setText("Create New Invoice");

        deleteInvoice.setText("Delete Invoice");

        invoiceNumber.setText("InvoiceNumber");

        invoiceDate.setText("InvoiceDate");

        customerName.setText("CustomerName");

        totalOfInvoice.setText("TotalOfInvoice");

        invoiceDateLable.setText("jLabel6");

        customerNameLable.setText("jLabel7");

        totalOfInvoiceLable.setText("jLabel8");

        lineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(lineTable);

        CreateItem.setText("Create New Item");

        deleteItem.setText("Delete Item");

        jMenu1.setText("File");

        loadFile.setText("Load File");
        jMenu1.add(loadFile);

        saveFile.setText("Save File");
        jMenu1.add(saveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createNewIvoice)
                        .addGap(90, 90, 90)
                        .addComponent(deleteInvoice))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CreateItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                                .addComponent(deleteItem))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(226, 226, 226))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(invoiceNumber)
                                .addGap(18, 18, 18)
                                .addComponent(InvoiceNumLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(customerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(customerNameLable))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(totalOfInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(totalOfInvoiceLable))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(invoiceDateLable)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoiceNumber)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(InvoiceNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceDate)
                            .addComponent(invoiceDateLable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerName)
                            .addComponent(customerNameLable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalOfInvoice)
                            .addComponent(totalOfInvoiceLable))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteItem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CreateItem)
                        .addComponent(deleteInvoice)
                        .addComponent(createNewIvoice)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameOfInvoice().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InvoiceNumLbl;
    private javax.swing.JButton CreateItem;
    private javax.swing.JButton createNewIvoice;
    private javax.swing.JLabel customerName;
    private javax.swing.JLabel customerNameLable;
    private javax.swing.JButton deleteInvoice;
    private javax.swing.JButton deleteItem;
    private javax.swing.JLabel invoiceDate;
    private javax.swing.JLabel invoiceDateLable;
    private javax.swing.JLabel invoiceNumber;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lineTable;
    private javax.swing.JMenuItem loadFile;
    private javax.swing.JMenuItem saveFile;
    private javax.swing.JTable tableOfInvoice;
    private javax.swing.JLabel totalOfInvoice;
    private javax.swing.JLabel totalOfInvoiceLable;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Invoice_Generator>Invoices;
    private ControllerOfSalesInvoice InvoiceController = new ControllerOfSalesInvoice(this) ;
    //private TableOfInvoice TableOfInvoice;
    private InvoicesTable tableofinvoicemodel;
    private LinesTable tableoflinesmodel;

    public InvoicesTable getTableofinvoicemodel() {
        if(tableofinvoicemodel==null)
        {
           tableofinvoicemodel = new InvoicesTable(getInvoices());
        }
        return tableofinvoicemodel;
    }

    public void setTableofinvoicemodel(InvoicesTable tableofinvoicemodel) {
        this.tableofinvoicemodel = tableofinvoicemodel;
    }

    public LinesTable getTableoflinesmodel() {
        return tableoflinesmodel;
    }
    
    

    public JTable getTableOfInvoice() {
        return tableOfInvoice;
    }
    

    public JTable getLineTable() {
        return lineTable;
    }

    public JLabel getInvoiceNumLbl() {
        return InvoiceNumLbl;
    }

    public JLabel getCustomerName() {
        return customerName;
    }

    public JLabel getCustomerNameLbl() {
        return customerNameLable;
    }

    public JLabel getInvoiceDate() {
        return invoiceDate;
    }

    public JLabel getInvoiceDateLbl() {
        return invoiceDateLable;
    }

    public JLabel getInvoiceNumber() {
        return invoiceNumber;
    }

    public JLabel getTotalOfInvoice() {
        return totalOfInvoice;
    }

    public JLabel getTotalOfInvoiceLable() {
        return totalOfInvoiceLable;
    }

    public ControllerOfSalesInvoice getInvoiceController() {
        return InvoiceController;
    }
    
    
   

    public ArrayList<Invoice_Generator> getInvoices() {
        if(Invoices == null)
            Invoices=new ArrayList<>();
        return Invoices;
    }

    public void setInvoices(ArrayList<Invoice_Generator> Invoices) {
        this.Invoices = Invoices;
    }
    
    public int getNextInvoiceNumber()
    {
       int number=0;
       for(Invoice_Generator invoice : getInvoices())
       {
          if(invoice.getNum() > number)
              number=invoice.getNum();
       }
       return ++number;
    }
    
}


